### ISSUE TITLE
[GameMemReader]: GameMemReader has encountered a problem.

### ISSUE THREAD

**Issue by Hybris95** [TauAkiou/amonguscapture-gtk#10]
I successfully compiled and started the program.
The hook on the game process seems to work.
But then, I received the following error, and the current state of the game is always "Disconnected".

> [GameMemReader]: Connected to Among Us process (10259)
> [GameVerifier]: Game Version Check: PASS
> [GameVerifier]: Game Validity Check: PASS
> [GameMemReader]: GameMemReader has encountered a problem. Please restart the program.

OS :
`Linux pop-os 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

I'm using Proton Experimental from Steam directly.

**Comment by Hybris95** [comment]
Here are the gtk versions installed on my OS :

>   Installé : 2.24.32-4ubuntu4
>   Installé : 3.24.23-1ubuntu1

  
  By the way, don't know if this could be an issue but i'm on KDE Plasma not Gnome

>   KDE Plasma : 5.19.5
>   KDE Frameworks : 5.74.0

And here are the dotnet versions installed :

> SDK .NET (reflétant tous les fichiers global.json) :
>  Version:   5.0.101
>  Commit:    d05174dc5a
> 
> Environnement d'exécution :
>  OS Name:     pop
>  OS Version:  20.10
>  OS Platform: Linux
>  RID:         linux-x64
>  Base Path:   /snap/dotnet-sdk/106/sdk/5.0.101/
> 
> Host (useful for support):
>   Version: 5.0.1
>   Commit:  b02e13abab
> 
> .NET SDKs installed:
>   5.0.101 [/snap/dotnet-sdk/106/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.1 [/snap/dotnet-sdk/106/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.1 [/snap/dotnet-sdk/106/shared/Microsoft.NETCore.App]

**Comment by Hybris95** [comment]
The only log received from capture software is the next one.
It happens before the Among Us process is even started.
Don't know if this could be linked to my issue though.

> (AmongUsCapture:9531): IBUS-WARNING **: 06:56:57.391: Unable to connect to ibus: Impossible de se connecter : Connexion refusée

Translation :

> Unable to connect : Connection refused

Edit :
I could start the IBUS daemon, the issue still occurs.
This log is clearly not linked to the issue encountered.

**Comment by Hybris95** [comment]
Here is the detailed StackTrace I could produce from a modified version of the source code :

> [GameMemReader-Message]: Exception of type 'AmongUsCapture.ProcessMemory+CaptureMemoryException' was thrown.
> [GameMemReader-StackTrace]:    at AmongUsCapture.ProcessMemoryLinux.OffsetAddress(IntPtr& address, Int32[] offsets)
> [GameMemReader-StackTrace]:    at AmongUsCapture.ProcessMemoryLinux.ReadWithDefault[T](IntPtr address, T defaultParam, Int32[] offsets)
> [GameMemReader-StackTrace]:    at AmongUsCapture.ProcessMemoryLinux.Read[T](IntPtr address, Int32[] offsets)
> [GameMemReader-StackTrace]:    at AmongUsCapture.GameMemReader.RunLoop()

**Comment by Hybris95** [comment]
There is only one call to Read method done on my execution.
And it generates the exception encountered :

> [ProcessMemory-Read]: Read<int>(GameAssemblyPtr, _gameOffsets.HudManagerOffset, 0x5C, 0, 0x28, 0xC, 0x14, 0x10)

So if I understand well, any call to "Read" method of ProcessMemory object will cause an exception throw.

**Comment by Hybris95** [comment]
And here are the details of ErrorNumber and ReadStatus recovered inside the OffsetAddress method of ProcessMemoryLinux :

> ErrorNumber: 14
> ReadStatus: -1

I will try to find out what ErrorNumber 14 means for Marshal class.

Edit : Seems like ErrorNumber 14 references an OutOfMemory issue :
https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

Edit (2) : Obviously I have enough memory available for this process, clearly don't know where the issue could come from..

**Comment by TauAkiou** [comment]
How much memory do you have on your system?

**Comment by TauAkiou** [comment]
I haven't looked into this for awhile - I don't really have access to a Linux system at the moment (stuck doing window dev right now).

There was someone before that only had 8GB of memory that had trouble running everything at the same time, but I presume there might be something else wrong with the latest release of Proton.

I will look into it.

**Comment by Hybris95** [comment]
Btw I have 32GB of RAM on my computer, I'm not sure this is really an issue of available memory on the system :D
Also, you can close the issue, I reinstalled my computer under Windows meanwhile.

**Comment by yoangau** [comment]
I encountered the same problem under arch linux
