### ISSUE TITLE
wrong state capture after updating among us

### ISSUE THREAD

**Issue by ervitis** [TauAkiou/amonguscapture-gtk#12]
After updating among us to version 2021.3.5, the Among Us capture program state is set to state "TASKS" when it runs.

2 days ago there was an update on amonguscapture repo, could it be related to? https://github.com/automuteus/amonguscapture/pull/164

**Comment by TauAkiou** [comment]
it's likely that some major changes happened to the memory/connection logic from the 2021.3.05 update.

this version really should be retired and reforked from the latest release, but i haven't had the energy to work on it.

**Comment by ervitis** [comment]
I see, do you plan on working on it and continue this awesome project?

**Comment by TauAkiou** [comment]
ideally, we should really should retool the GTK UI using the latest version from master. the Linux memory reader code was merged a long time ago, and this version is mostly built around an older version of the core AmongUsCapture code with some current features sort of hacked in.

i've wanted to make some progress on this for awhile, but some personal issues have made things difficult there.

**Comment by ervitis** [comment]
No problem, I hope everything is ok. Thank you for taking time replying me! Regards

**Comment by TauAkiou** [comment]
i made an update to this - if you want to help test, checkout the 'current-version' branch and see if it works. This implements the memory code from the latest version of amonguscapture which should allow this to work again.

**Comment by TauAkiou** [comment]
This issue will be closed, as it is related to v1.0, which is no longer being worked on.
