### ISSUE TITLE
Does not capture game

### ISSUE THREAD

**Issue by dominx99** [TauAkiou/amonguscapture-gtk#3]
I am using the `master` branch
I am working on `Arch Linux`
I am using `wine` to run among us from steam

I have game opened
Among Us Capture Gtk opened
It connects to Auto Mute Us Discord Bot perfect, but it's not capturing game code and state

I was also testing a `linux-mem-new` branch and it detected the current state as "discussion" (code was still empty) when I was in lobby.

![image](https://user-images.githubusercontent.com/25711467/97204883-f497ae00-17b6-11eb-838f-d994443b663f.png)
![image](https://user-images.githubusercontent.com/25711467/97205418-c5ce0780-17b7-11eb-8b59-d05e149f4c86.png)
![image](https://user-images.githubusercontent.com/25711467/97205040-2dd01e00-17b7-11eb-8fa4-51a2340adea1.png)

**Comment by dominx99** [comment]
I downloaded `v1.1.0-gtk` release
It detects lobby as discusion and code also is empty

![image](https://user-images.githubusercontent.com/25711467/97208286-417d8380-17bb-11eb-9319-30c99c97a243.png)
![image](https://user-images.githubusercontent.com/25711467/97208231-30347700-17bb-11eb-8cbd-3b2ae259c35f.png)
![image](https://user-images.githubusercontent.com/25711467/97208558-8d302d00-17bb-11eb-9f25-c4e55d53f978.png)

**Comment by jasikpark** [comment]
why was this closed? I am having the same problem.

**Comment by dominx99** [comment]
sudo did the trick

**Comment by jasikpark** [comment]
hmm i'll have to try that

**Comment by TauAkiou** [comment]
This is something that I've seen before with someone else, and I haven't been able to replicate it.

I tried replicating the problem on my own Ubuntu install, but it worked perfectly there, too.

**Comment by jasikpark** [comment]
I use Ubuntu 20.14 - and using sudo solved my problems with it not grabbing the capture data

You can see in #4 that it didn't work for the prerelease though!

**Comment by jasikpark** [comment]
I was able to run `sudo setcap cap_sys_ptrace=eip <executable>` and it works now

**Comment by TauAkiou** [comment]
I'll be adding a notification to the readme and pushing some additional error checks for the memory backend alongside the DBus release.

**Comment by TauAkiou** [comment]
v1.1.1-gtk adds some checking for this issue, and a notification to README.md telling you how you can fix it.
