### ISSUE TITLE
Capture no longer works - does 2020.10.22 have new offsets? 

### ISSUE THREAD

**Issue by jasikpark** [TauAkiou/amonguscapture-gtk#6]
![Screenshot from 2020-11-02 23-23-28](https://user-images.githubusercontent.com/10626596/97952866-5da59580-1d64-11eb-9176-4d32339bfcfa.png)
![Screenshot from 2020-11-02 23-23-21](https://user-images.githubusercontent.com/10626596/97952867-5e3e2c00-1d64-11eb-915a-df5ff6d66178.png)

How can I merge https://github.com/denverquane/amonguscapture/commit/bfeeb9aa873e6bfcc01b2dd9d5f2816222e9bade somehow?

**Comment by TauAkiou** [comment]
you can add the offsets into ~/.config/AmongUsCapture/settings.json. I'm going to polish up v1.2.0 and release that with the new offsets.

**Comment by TauAkiou** [comment]
@jasikpark Try inserting this JSON file into ~/.config/AmongUsCapture - it should work until I release the new version. (Rename it to GameOffsets.json)

[GameOffsets.txt](https://github.com/TauAkiou/amonguscapture-gtk/files/5484548/GameOffsets.txt)

**Comment by jasikpark** [comment]
Sweet! I’ll try that out thanks a lot

Caleb Jasik
calebjasik@jasik.xyz
https://jasik.xyz

On November 3, 2020 at 4:47:47 PM, TauAkiou (notifications@github.com) wrote:

you can add the offsets into ~/.config/AmongUsCapture/settings.json. I'm going to polish up v1.2.0 and release that with the new offsets.

**Comment by TauAkiou** [comment]
Released capture 1.2.0-gtk.
