### ISSUE TITLE
Changes required for 2020.11.17s (Release 2) 

### ISSUE THREAD

**Issue by dsjoho** [TauAkiou/amonguscapture-gtk#7]
New release of the game seems to require new offsets, and some other change.. Cause my GameMemReader crashes even if I patch in the correct offsets from 
https://github.com/denverquane/amonguscapture/blob/7b697f67aadaf846f0a7b482f82502867d824147/AmongUsCapture/Settings.cs

**Comment by TauAkiou** [comment]
it's likely failing because the hash was incorrect (and not in sha256 - the sha256 change was recent).

Please try this beta release and see if it works; https://github.com/TauAkiou/amonguscapture-gtk/actions/runs/401914001

**Comment by dsjoho** [comment]
Seems to work: at least it detected Menu and the room code when i tried it solo.
Did have to reverting the change in AmongUsCapture/AmongUsCapture.csproj, since I haven't found a packaged dotnet 5.0 packaged. I.e. I kept netcoreapp3.1 as TargetFramework.

So I didn't check the code - does it refuse to work  if the gamehash is incorrect? I never bothered to update that, only the offsets.

**Comment by TauAkiou** [comment]
i'm thinking there's some kind of error in the pause code that causes it to die the way it does. something I can look into, but I'm still working on a new version that uses the latest codebase from the original master, so I don't know if I'll get around to fixing it.

**Comment by dsjoho** [comment]
Nah that sounds fine, it seems to work now (even though I haven't fully playtested it) - and that sounds like sound priorities.
Thanks for the quick fix and your work!

**Comment by TauAkiou** [comment]
Automatic updating should now be included with v1.2.1. Closing this.
