### ISSUE TITLE
Not running on windows

### ISSUE THREAD

**Issue by oxodao** [TauAkiou/amonguscapture-gtk#9]
Hi,

I have had no issue running it on Linux (at least starting the software, it couldn't hook onto the game for some reasons even if I added amonguscapture's bindings which are supposedly compatible to 2020.12.9) but when running on windows I have no issue compiling it but no window shows up, and nothing is logged in the powershell prompt, both in debug and release build

I have installed both dotnet core 3.1 and 5.0 but it seems to compile with 5.0

**Comment by TauAkiou** [comment]
I recommend using the official release for Windows, as stated in the readme.

if you're not seeing a window, make sure you've installed the GTK+ runtime linked in the comments.

**Comment by oxodao** [comment]
Standard version is too much bloated UI-wise and I don't want to have to change it that much, I quite like the one from this repo, plus GTK is better than WPF / windows official things

Pretty sure GTK+ runtime is set up correctly so I don't know what's wrong there :/

Thanks anyway..

**Comment by TauAkiou** [comment]
Did you install GTK2 by mistake? This is a GTK3+ app. That's the only reason I can think of as to why it won't run, as it still works on my Windows install (barring a few fixes I just made)

**Comment by TauAkiou** [comment]
This issue will be closed, as it is related to v1.0, which is no longer being worked on.
